name: LegendaryClans
main: me.blackhawklex.legendaryclans.LegendaryClans
version: 0.16.1
website: http://www.landoflegend.net
author: [LandofLegend Custom Development Team, Dionnsai, BlackHawkLex ]
description: LandofLegend Custom Clan/Party System, Server Functions, Mob Loot and Handling, More...

commands:
  clan:
    description: Basic clan function
    aliases: []
    usage: /<command> 
  party:
    description: basic party function
    aliases: ['lparty','lp']
    usage: /<command>
  aclan:
    description: admin clan commands
    aliases: []
    usage: /<command>
  ch:
    description: basic chat commands
    aliases: ['channel']
    usage: |
  don:
    description: admin command for donation management
    aliases: []
    usage: |

depend: [Spout,WorldGuard,iConomy,Vault,Citizens,SpoutShops,SpoutMaterials,LoginQueue2,DungeonBuilder]

