name: LegendaryClans
main: me.blackhawklex.legendaryclans.LegendaryClans
version: 1.0
website: http://
author: BlackHawkLex


description: >
             See what we can work out.
commands:
  clan:
    description: Basic clan function
    aliases: []
    usage: |
           /<command> 
  party:
    description: basic party function
    aliases: []
    usage: |
           /<command>
  aclan:
    description: admin clan commands
    aliases: []
    usage: |
    
  ch:
    description: basic chat commands
    aliases: []
    usage: |
    
  don:
    description: admin command for donation management
    aliases: []
    usage: |
depend: [Spout,WorldGuard,iConomy,Vault,Citizens,SpoutShops,SpoutMaterials,LoginQueue2,DungeonBuilder]

